-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE wo_fandom_import (
  wofi_id SERIAL NOT NULL,
  wofi_source TEXT NOT NULL,
  wofi_dbname TEXT NOT NULL,
  wofi_sitename TEXT NOT NULL,
  wofi_language TEXT NOT NULL,
  wofi_category TEXT DEFAULT '' NOT NULL,
  wofi_mode TEXT NOT NULL,
  wofi_reason TEXT NOT NULL,
  wofi_fandom_user TEXT DEFAULT '' NOT NULL,
  wofi_requester INT NOT NULL,
  wofi_reviewer INT DEFAULT 0 NOT NULL,
  wofi_status TEXT NOT NULL,
  wofi_stage TEXT DEFAULT '' NOT NULL,
  wofi_progress TEXT NOT NULL,
  wofi_info TEXT NOT NULL,
  wofi_error TEXT NOT NULL,
  wofi_files_expire TIMESTAMPTZ DEFAULT NULL,
  wofi_created TIMESTAMPTZ NOT NULL,
  wofi_updated TIMESTAMPTZ NOT NULL,
  PRIMARY KEY(wofi_id)
);

CREATE INDEX wofi_source ON wo_fandom_import (wofi_source, wofi_id);

CREATE INDEX wofi_dbname ON wo_fandom_import (wofi_dbname);

CREATE INDEX wofi_status_updated ON wo_fandom_import (wofi_status, wofi_updated);

CREATE INDEX wofi_requester_updated ON wo_fandom_import (wofi_requester, wofi_updated);
