-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wo_fandom_import (
  wofi_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  wofi_source BLOB NOT NULL,
  wofi_dbname BLOB NOT NULL,
  wofi_sitename BLOB NOT NULL,
  wofi_language BLOB NOT NULL,
  wofi_category BLOB DEFAULT '' NOT NULL,
  wofi_mode BLOB NOT NULL,
  wofi_reason BLOB NOT NULL,
  wofi_fandom_user BLOB DEFAULT '' NOT NULL,
  wofi_requester INTEGER UNSIGNED NOT NULL,
  wofi_reviewer INTEGER UNSIGNED DEFAULT 0 NOT NULL,
  wofi_status BLOB NOT NULL,
  wofi_stage BLOB DEFAULT '' NOT NULL,
  wofi_progress BLOB NOT NULL,
  wofi_info BLOB NOT NULL,
  wofi_error BLOB NOT NULL,
  wofi_files_expire BLOB DEFAULT NULL,
  wofi_created BLOB NOT NULL,
  wofi_updated BLOB NOT NULL
);

CREATE INDEX wofi_source ON /*_*/wo_fandom_import (wofi_source, wofi_id);

CREATE INDEX wofi_dbname ON /*_*/wo_fandom_import (wofi_dbname);

CREATE INDEX wofi_status_updated ON /*_*/wo_fandom_import (wofi_status, wofi_updated);

CREATE INDEX wofi_requester_updated ON /*_*/wo_fandom_import (wofi_requester, wofi_updated);
