-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wo_fandom_import (
  wofi_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  wofi_source VARBINARY(128) NOT NULL,
  wofi_dbname VARBINARY(64) NOT NULL,
  wofi_sitename VARBINARY(255) NOT NULL,
  wofi_language VARBINARY(35) NOT NULL,
  wofi_category VARBINARY(64) DEFAULT '' NOT NULL,
  wofi_mode VARBINARY(8) NOT NULL,
  wofi_reason BLOB NOT NULL,
  wofi_fandom_user VARBINARY(255) DEFAULT '' NOT NULL,
  wofi_requester INT UNSIGNED NOT NULL,
  wofi_reviewer INT UNSIGNED DEFAULT 0 NOT NULL,
  wofi_status VARBINARY(16) NOT NULL,
  wofi_stage VARBINARY(16) DEFAULT '' NOT NULL,
  wofi_progress BLOB NOT NULL,
  wofi_info BLOB NOT NULL,
  wofi_error BLOB NOT NULL,
  wofi_files_expire BINARY(14) DEFAULT NULL,
  wofi_created BINARY(14) NOT NULL,
  wofi_updated BINARY(14) NOT NULL,
  INDEX wofi_source (wofi_source, wofi_id),
  INDEX wofi_dbname (wofi_dbname),
  INDEX wofi_status_updated (wofi_status, wofi_updated),
  INDEX wofi_requester_updated (wofi_requester, wofi_updated),
  PRIMARY KEY(wofi_id)
) /*$wgDBTableOptions*/;
